FROM golang:1.8

LABEL maintainer="marc.siebeneicher@trivago.com"
LABEL maintainer="arne.claus@trivago.com"

# install base packages / dependencies
RUN apt-get update \
    && apt-get install --no-install-recommends -y make git

# install pcap
RUN apt-get install -y libc-dev libpcap-dev

# install librdkafka
ADD http://launchpadlibrarian.net/234454186/librdkafka1_0.8.6-1.1_amd64.deb /src/librdkafka1_0.8.6-1.1_amd64.deb
ADD http://launchpadlibrarian.net/234454185/librdkafka-dev_0.8.6-1.1_amd64.deb /src/librdkafka-dev_0.8.6-1.1_amd64.deb

RUN dpkg -i /src/librdkafka1_0.8.6-1.1_amd64.deb \
    && dpkg -i /src/librdkafka-dev_0.8.6-1.1_amd64.deb

# install go dependencies
RUN go get -u github.com/golang/lint/golint

# cleanup
RUN rm -rf /var/lib/apt/lists/*

# copy code
COPY . /go/src/github.com/trivago/gollum/

# install gollum
WORKDIR /go/src/github.com/trivago/gollum
RUN cp contrib_loader.go.dist contrib_loader.go

RUN make current \
    && ln -s /go/src/github.com/trivago/gollum/gollum /usr/local/bin/gollum

# set ENTRYPOINT
ENTRYPOINT ["/usr/local/bin/gollum"]