#!/bin/bash

RunTests()
{
  if ls $1/*_test.go 1> /dev/null 2>&1; then
    go test $1
    if [ $? != 0 ]; then
      errors=$((errors+1))
    fi
  fi

  for name in $1/* ; do
    if [ -d $name ]; then
      RunTests $name
    fi
  done
}

errors=0
RunTests $1
exit $errors
